### ISSUE TITLE
Filter problems

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTProblems.jl#13]
I have added the possibility to filter the problems you want to get, for instance to make some tests.

You simply have to define a logical condition with the combination of symbols and three operators: `!`, `|` and `&`, respectively for the negation, the disjunction and the conjunction. 

Here is an example to get the problems whom description does not contain the pair `:exponential` and `:energy`, or contains `:toto`:

```julia
@Problems !(:exponential & :energy) | :toto
```

Would it be better to define the following operators?

- `!`
- `||`
- `&&`

Something else?

**Comment by jbcaillau** [comment]
👍🏽 since there is no [short circuit](https://docs.julialang.org/en/v1/manual/control-flow/#Short-Circuit-Evaluation) semantics, `&` and `|` seem fine
