### ISSUE TITLE
Tag state_constraint for Goddard

### ISSUE THREAD

**Issue by PierreMartinon** [control-toolbox/CTProblems.jl#7]
It appears goddard now uses box constraints instead of state constraints. Tag needs to be updated.
Also the labels for each constraints should clearly indicate the type, ie box / control / state / mixed.
(it can get quite confusing when trying to parse the constraints)

More generally, I think it is better to add new versions of the same problem instead of modifying existing ones, since the tags are not correct anymore. For instance there could be 2 goddard, one with state/control constraints and one with box constraints (could even have one with only mixed constraints for comparison). One can of course manually change the constraints of a problem for specific testing but this is quite unpractical.

**Comment by ocots** [comment]
Add Goddard with all constraints types.
